### ISSUE TITLE
ERROR:  Could not find a valid gem 'integratej2objc' (>= 0) in any repository

### ISSUE THREAD

**Issue by confile** [developertown/integratej2objc#1]
I tried to install your plugin but got the following error: 

```
ERROR:  Could not find a valid gem 'integratej2objc' (>= 0) in any repository
```

**Comment by confile** [comment]
Probably you did not deploy it. Locally it works fine.

**Comment by jonnolen** [comment]
I did not deploy it... will deploy it after it gets a little more polished.  right I'm installing it and running it via bundler:
Gemfile:
```
source "https://rubygems.org"

gem 'integratej2objc', git:'https://github.com/developertown/integratej2objc.git'
```

bundle; bundle exec integratej2objc help;

**Comment by jonnolen** [comment]
I've updated the read me with the better installation instructions., closing this.  added #3 to track deploying to rubygems in the future.

**Comment by confile** [comment]
@jonnolen I tried: 

```
gem install 'integratej2objc', git:'https://github.com/developertown/integratej2objc.git'
```

but still I do not get a proper install. The output is: 

```
ERROR:  Could not find a valid gem 'integratej2objc,' (>= 0) in any repository
ERROR:  Possible alternatives: integration, integrator, integrity-bob, integrity-jabber
ERROR:  Could not find a valid gem 'git:https://github.com/developertown/integratej2objc.git' (>= 0) in any repository

```
